---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-sd4776-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: 'Microservice for dev environment'
  destinations:
  - name: '*'
    namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  sourceRepos:
  - '*'
  - ""
